# Generated by Django 6.0.3 on 2026-03-18 15:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(db_comment='SHA-256 hash — never store the raw key', help_text='SHA-256 hex digest of the raw API key', max_length=64, unique=True)),
                ('name', models.CharField(help_text="Human-readable label for this key (e.g. 'CI pipeline')", max_length=100)),
                ('permissions', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], db_index=True, default='read', max_length=10)),
                ('last_used', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last successful authenticated request', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiry; null means no expiration', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_apikey_user_active'), models.Index(fields=['expires_at'], name='idx_apikey_expires')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Change'), ('config_change', 'Config Change'), ('trade_pause', 'Trade Pause'), ('trade_resume', 'Trade Resume'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('permission_change', 'Permission Change'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, unpack_ipv4=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Arbitrary structured context for the event (JSONB in PostgreSQL)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(blank=True, help_text='Null for unauthenticated or deleted-user events', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['action', 'timestamp'], name='idx_auditlog_action_ts'), models.Index(fields=['user', 'timestamp'], name='idx_auditlog_user_ts'), models.Index(fields=['ip_address', 'timestamp'], name='idx_auditlog_ip_ts')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(db_comment='UUID primary key for UserProfile', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('trader', 'Trader'), ('viewer', 'Viewer')], db_comment='Role determines dashboard access level', db_index=True, default='viewer', max_length=10)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Telegram chat ID for trade notifications', max_length=50, null=True)),
                ('notification_enabled', models.BooleanField(default=True, help_text='Enable/disable all platform notifications')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='TOTP-based 2FA status (managed via django-allauth)')),
                ('last_active', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last authenticated request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['role'], name='idx_userprofile_role'), models.Index(fields=['last_active'], name='idx_userprofile_last_active')],
            },
        ),
    ]
