# Generated by Django 6.0.3 on 2026-03-18 15:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('connected_to_mt5', models.BooleanField(default=False)),
                ('last_scan_time', models.DateTimeField(blank=True, null=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('account_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_losses', models.IntegerField(default=0)),
                ('daily_loss_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Status',
                'verbose_name_plural': 'Bot Status',
                'db_table': 'bot_status',
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('trades', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('scratches', models.IntegerField(default=0)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ai_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('best_trade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('worst_trade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SRLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('strength', models.IntegerField(db_index=True, default=1)),
                ('timeframes', models.JSONField(default=list)),
                ('session_touches', models.IntegerField(default=0)),
                ('first_detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_touched', models.DateTimeField(blank=True, null=True)),
                ('traded', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'sr_levels',
                'ordering': ['-strength', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'strength'], name='sr_levels_symbol_55507f_idx'), models.Index(fields=['symbol', 'price'], name='sr_levels_symbol_6e1f8a_idx'), models.Index(fields=['traded'], name='sr_levels_traded_72da75_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pnl', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('entry_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('bars_held', models.IntegerField(blank=True, null=True)),
                ('level_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('level_strength', models.IntegerField(blank=True, null=True)),
                ('level_timeframes', models.CharField(blank=True, default='', max_length=200)),
                ('scout_action', models.CharField(blank=True, default='', max_length=10)),
                ('scout_confidence', models.IntegerField(blank=True, null=True)),
                ('scout_reason', models.TextField(blank=True, default='')),
                ('confirmer_action', models.CharField(blank=True, default='', max_length=10)),
                ('confirmer_confidence', models.IntegerField(blank=True, null=True)),
                ('confirmer_reason', models.TextField(blank=True, default='')),
                ('exit_reason', models.TextField(blank=True, default='')),
                ('filters_log', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-entry_time'],
                'indexes': [models.Index(fields=['symbol', 'entry_time'], name='trades_symbol_3e71f1_idx'), models.Index(fields=['pnl'], name='trades_pnl_27dfc6_idx'), models.Index(fields=['entry_time'], name='trades_entry_t_08ab99_idx')],
            },
        ),
    ]
