# Generated by Django 6.0.3 on 2026-03-18 15:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.UUIDField(db_comment='Unique decision identifier (UUID v4)', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_comment='UTC time the API call was initiated', db_index=True, default=django.utils.timezone.now)),
                ('symbol', models.CharField(db_comment='Forex pair / instrument, e.g. USDJPYm', db_index=True, max_length=20)),
                ('role', models.CharField(choices=[('scout', 'Scout'), ('confirmer', 'Confirmer'), ('exit', 'Exit Manager')], db_comment='Which AI agent made this call', db_index=True, max_length=10)),
                ('model', models.CharField(db_comment='Full OpenRouter model identifier, e.g. anthropic/claude-haiku-4.5', max_length=100)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SKIP', 'Skip'), ('CONFIRM', 'Confirm'), ('REJECT', 'Reject'), ('HOLD', 'Hold'), ('CLOSE', 'Close'), ('ERROR', 'Error')], db_comment='Parsed action from AI response', db_index=True, max_length=10)),
                ('confidence', models.IntegerField(db_comment='AI-reported confidence 0-100')),
                ('reason', models.TextField(db_comment='Plain-English reason extracted from AI response')),
                ('input_context', models.TextField(db_comment='Full serialised context dict sent to the AI (JSON string)')),
                ('raw_response', models.TextField(db_comment='Raw text body returned by the OpenRouter API')),
                ('latency_ms', models.IntegerField(db_comment='Round-trip API latency in milliseconds')),
                ('cost_usd', models.DecimalField(db_comment='Estimated USD cost for this single API call', decimal_places=6, max_digits=10)),
            ],
            options={
                'verbose_name': 'AI Decision',
                'verbose_name_plural': 'AI Decisions',
                'db_table': 'ai_decisions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'role', '-timestamp'], name='ai_decision_symbol_0acded_idx'), models.Index(fields=['model', '-timestamp'], name='ai_decision_model_523f72_idx'), models.Index(condition=models.Q(('action__in', ['BUY', 'SELL', 'CONFIRM'])), fields=['symbol', 'action'], name='ai_decisions_active_idx')],
            },
        ),
    ]
